In [6]:
from src.load_data import load_csv
from src.preprocessing import clean_text
from src.preprocessing import clean_dataframe
import pandas as pd

In [2]:
df1 = load_csv('../data_raw/ViHealthQA/train.csv')
df2 = load_csv('../data_raw/ViHealthQA/test.csv')
df3 = load_csv('../data_raw/ViHealthQA/val.csv')

In [3]:
df1.head()

,id,question,answer,link
0,1,Đang chích ngừa viêm gan B có chích ngừa Covid...,Nếu anh/chị đang tiêm ngừa vaccine phòng bệnh ...,https://vnexpress.net/tu-van-tiem-vaccine-covi...
1,2,"Đau đầu, căng thẳng do công việc, suy giảm trí...",Tình trạng đau đầu theo bạn mô tả thì chưa rõ....,https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
2,3,Đặt lưu lượng khí hệ thống Jackson-Rees thấp h...,Hệ thống Jackson – Rees dùng khi gây mê để trá...,https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
3,4,Bé 13 tháng tuổi uống thuốc Acyclovir có được ...,Acyclovir có thể sử dụng cho cả trẻ dưới 13 th...,https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
4,5,Vừa qua ngày 4/6 tôi có bị con chó ở nhà cắn x...,Bệnh dại là bệnh nguy hiểm và nếu có chỉ định ...,https://vnexpress.net/tu-van-tiem-vaccine-covi...

In [4]:
df2.head()

,id,question,answer,link
0,1,"Trẻ sốt, ăn kém, chướng bụng phình to cảnh báo...",Tình trạng kém ăn của bé cũng có thể do bé đan...,https://www.vinmec.com/vi/tin-tuc/hoi-dap-bac-...
1,2,Mạch máu nổi ở tinh hoàn bên trái là biểu hiện...,Bạn xuất hiện nhiều mạch máu nổi ở bìu bên trá...,https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
2,3,"Trẻ 3 tháng tuổi đi phân nhầy, xanh có đáng lo...","Bé của bạn ngoài đi phân đôi khi có màu xanh, ...",https://www.vinmec.com/vi/tin-tuc/hoi-dap-bac-...
3,4,Bị đau đầu do u não có nghiêm trọng không?,Xin khuyến cáo bạn đưa người nhà đi khám ngay ...,https://www.vinmec.com/vi/tin-tuc/hoi-dap-bac-...
4,5,Nhịp tim của tôi bình thường khoảng 50-55 nhịp...,"Trường hợp của anh/chị, nhịp tim chậm, cần phả...",https://vnexpress.net/tu-van-tiem-vaccine-covi...

In [5]:
df3.head()

,id,question,answer,link
0,1,Em nghe nói kích trứng nhiều lần sẽ làm rối lo...,Theo thông tin chị cung cấp thì chưa đủ dữ liệ...,https://vnexpress.net/tu-van-vo-sinh-hiem-muon...
1,2,Tại sao tỷ lệ dịch chuyển tinh trùng thấp?,Nguyên nhân dẫn đến tỷ lệ dịch chuyển tinh tr...,https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
2,3,Ngồi dậy hay nằm xuống đều bị chóng mặt có phả...,"Xương đòn khi mổ rất lâu liền xương, 3 tuần ch...",https://www.vinmec.com/vi/suc-khoe-tong-quat/t...
3,4,"Hàng ngày, tôi uống thuốc huyết áp hỗ trợ điều...",Nếu huyết áp sau điều trị ổn định ở mức huyết ...,https://vnexpress.net/tu-van-tiem-vaccine-covi...
4,5,Co giật có phải dấu hiệu của Viêm não Nhật Bản...,"Vì chị không nói rõ bé ở độ tuổi nào, các cơn ...",https://www.vinmec.com/vi/tin-tuc/hoi-dap-bac-...

In [7]:
# Gộp 3 tập train, test, val thành một bộ dữ liệu lớn
df_all = pd.concat([df1, df2, df3], ignore_index=True)

# Loại bỏ cột 'id' và 'link' nếu không cần thiết cho việc huấn luyện mô hình
df_all = df_all[['question', 'answer']]

# Sử dụng hàm clean_dataframe (giả định hàm này xử lý null và áp dụng clean_text)
# Nếu chưa có, bạn có thể áp dụng trực tiếp:
df_all = df_all.dropna()
df_all['question'] = df_all['question'].apply(clean_text)
df_all['answer'] = df_all['answer'].apply(clean_text)

# Loại bỏ trùng lặp
df_all = df_all.drop_duplicates()

In [8]:
# Lưu CSV (Sử dụng utf-8-sig để hiển thị tốt trên Excel)
df_all.to_csv('../data_clean/ViHealthQA_combined_cleaned.csv', index=False, encoding='utf-8-sig')

# Lưu JSON (orient='records' để tạo danh sách các object)
df_all.to_json('../data_clean/ViHealthQA_combined_cleaned.json', orient='records', force_ascii=False, indent=4)

print(f"Tổng số dòng sau khi gộp và làm sạch: {len(df_all)}")

Tổng số dòng sau khi gộp và làm sạch: 10002